export const ProjectsData = [
    {
        id: 'PJ-0001',
        name: "Courses Design, Databases, Web Escentials, Javascript",
        type: "Backend-Frontend Developer & Designer TRAINEE",
        period: "2005 - 2007",
        startDate: 1136095200000,
        endDate: 1167631200000,
        duration: 2,
        durationFraction: '-5',
        description: "DES_0001",
        portfolioUrl: null,
        portfolioImage: null,
        technologiesId: ['HTML5', 'CSS3', 'MSSQL', 'JS', 'ABFLASH', 'MSNET'],
        level: 1,
        color: 'red',
    },
    {
        id: 'PJ-0002',
        name: "Sigsa Web Pages Events",
        type: "Backend-Frontend Developer & Designer JR",
        period: "2008 - 2009",
        startDate: 1199167200000,
        endDate: 1230789600000,
        duration: 0,
        durationFraction: '-5',
        description: "DES_0002",
        portfolioUrl: null,
        portfolioImage: null,
        technologiesId: [ 'HTML5', 'CSS3', 'JS', 'JQUERY', 'ABFLASH' ],
        level: 1,
        color: 'yellow'
    },
    {
        id: 'PJ-0003',
        name: "Sigsa Web Maps Geological Control",
        type: "Backend-Frontend Developer & Designer JR",
        period: "2009 - 2009",
        startDate: 1230789600000,
        endDate: 1230789600000,
        duration: 0,
        durationFraction: '-5',
        description: "DES_0003",
        portfolioUrl: null,
        portfolioImage: null,
        technologiesId: [ 'HTML5', 'CSS3', 'JS', 'JQUERY', 'ABFLASH', 'MSCSHARP' ],
        level: 2,
        color: 'blue'
    },
    {
        id: 'PJ-0004',
        name: "Expo-Robotica Web",
        type: "Frontend Developer & Designer JR",
        period: "2009 - 2009",
        startDate: 1230789600000,
        endDate: 1259647200000,
        duration: 0,
        durationFraction: '-5',
        description: "DES_0004",
        portfolioUrl: null,
        portfolioImage: null,
        technologiesId: [ 'HTML5', 'CSS3', 'JS', 'JQUERY', 'ABFLASH', 'MSCSHARP' ],
        level: 3,
        color: 'aqua',
    },

    {
        id: 'PJ-0005',
        name: "CFDi Electronic Billing",
        type: "Backend-Frontend Developer & Designer",
        period: "2009 - 2009",
        startDate: 1230789600000,
        endDate: 1230789600000,
        duration: 1,
        durationFraction: '',
        description: "DES_0005",
        portfolioUrl: null,
        portfolioImage: null,
        technologiesId: [ 'HTML5', 'CSS3', 'JS', 'JQUERY', 'NHIBERNATE', 'MSCSHARP', 'MSNET' ],
        level: 4,
        color: 'orange',
    },
    {
        id: 'PJ-0006',
        name: "Television Program Planner",
        type: "Backend-Frontend Developer & Designer",
        period: "2011 - 2011",
        startDate: 1293861600000,
        endDate: 1293861600000,
        duration: 0,
        durationFraction: '-5',
        description: "DES_0006",
        portfolioUrl: null,
        portfolioImage: null,
        technologiesId: [ 'MSNET', 'MSCSHARP', 'NHIBERNATE', 'MSWFM', 'JS', 'MSSQL', 'GIT' ],
        level: 1,
        color: 'orange',
    },
    {
        id: 'PJ-0007',
        name: "Expense and Income Reporter",
        type: "Backend-Frontend Developer & Designer",
        period: "2011 - 2011",
        startDate: 1293861600000,
        endDate: 1293861600000,
        duration: 0,
        durationFraction: '-5',
        description: "DES_0007",
        portfolioUrl: null,
        portfolioImage: null,
        technologiesId: [ 'HTML', 'JQuery', 'JS', 'JQUERY', 'MSCSHARP', 'CSS3', 'MSSQL', 'MSWPF' ],
        level: 2,
        color: 'blue',
    },
    {
        id: 'PJ-0008',
        name: "Actus Broker Insurance Management",
        type: "Backend-Frontend Developer & Designer",
        period: "2012 - 2013",
        startDate: 1325397600000,
        endDate: 1357020000000,
        duration: 1,
        durationFraction: '',
        description: "DES_0008",
        portfolioUrl: null,
        portfolioImage: null,
        technologiesId: [ 'HTML5', 'CSS3', 'JS', 'JQUERY', 'MSNET', 'MSCSHARP', 'NHIBERNATE', 'MSAZURE' ],
        level: 1,
        color: 'red',
        image: "img/blackboard.png",
    },
    {
        id: 'PJ-0009',
        name: "United States Embassy Reporter",
        type: "Backend-Frontend Developer & Designer",
        period: "2013 - 2014",
        startDate: 1357020000000,
        endDate: 1388556000000,
        duration: 0,
        durationFraction: '-5',
        description: "DES_0009",
        portfolioUrl: null,
        portfolioImage: null,
        technologiesId: [ 'HTML5', 'CSS3', 'JS', 'JQUERY', 'MSNET', 'MSCSHARP', 'MSWFM', 'GIT'],
        level: 2,
        color: 'red'
    },
    {
        id: 'PJ-0010',
        name: "AIG Insurance Management",
        type: "Backend-Frontend Developer & Designer",
        period: "2013 - 2014",
        startDate: 1357020000000,
        endDate: 1388556000000,
        duration: 0,
        durationFraction: '-5',
        description: "DES_0010",
        portfolioUrl: null,
        portfolioImage: null,
        technologiesId: [ 'HTML5', 'CSS3', 'JS', 'JQUERY', 'MSNET', 'MSCSHARP', 'MSWFM', 'GIT'],
        level: 3,
        color: 'red',
    },
    {
        id: 'PJ-0011',
        name: "METLIFE Insurance Management",
        type: "Backend-Frontend Developer & Designer",
        period: "2013 - 2014",
        startDate: 1357020000000,
        endDate: 1388556000000,
        duration: 0,
        durationFraction: '-5',
        description: "DES_0011",
        portfolioUrl: null,
        portfolioImage: null,
        technologiesId: [ 'HTML5', 'CSS3', 'JS', 'JQUERY', 'MSNET', 'MSCSHARP', 'MSWFM', 'GIT'],
        level: 4,
        color: 'red',
    },
    {
        id: 'PJ-0012',
        name: "Blackboard",
        type: "Web Developer",
        period: "SEP 2014 - AUG 2015",
        startDate: 1388556000000,
        endDate: 1420092000000,
        duration: 1,
        durationFraction: '',
        description: "DES_0012",
        portfolioUrl: null,
        portfolioImage: "img/blackboard.png",
        technologiesId: [ 'HTML5', 'SASS', 'JS', 'JQUERY', 'TS', 'NG', 'KARMA', 'JAZMINE', 'GIT', 'JIRA', 'CONFLUENCE', 'NODEJS', 'ABXD' ],
        level: 1,
        color: 'blue'
    },
    {
        id: 'PJ-0013',
        name: "Scholastic",
        type: "Web Developer / Backend Developer",
        period: "SEP 2015 - JUL 2016",
        startDate: 1420092000000,
        endDate: 1451628000000,
        duration: 1,
        durationFraction: '',
        description: "DES_0013",
        portfolioUrl: null,
        portfolioImage: "img/scholastic.png",
        technologiesId: [ 'HTML5', 'SASS', 'JS', 'JQUERY', 'TS', 'NG', 'KARMA', 'JAZMINE', 'GIT', 'JIRA', 'CONFLUENCE', 'NODEJS', 'ABXD' ],
        level: 2,
        color: 'orange',
    },
    {
        id: 'PJ-0014',
        name: "Interapt",
        type: "Web Developer / Backend Developer",
        period: "SEP 2016 - NOV 2016",
        startDate: 1451628000000,
        endDate: 1451628000000,
        duration: 0,
        durationFraction: '-5',
        description: "DES_0014",
        portfolioUrl: null,
        portfolioImage: "img/interapt.png",
        technologiesId: [ 'HTML5', 'SASS', 'JS', 'JQUERY', 'TS', 'NG', 'KARMA', 'JAZMINE', 'GIT', 'JIRA', 'CONFLUENCE', 'NODEJS', 'ABXD' ],
        level: 3,
        color: 'aqua',
    },
    {
        id: 'PJ-0015',
        name: "Ebay, VivaAnuncios",
        type: "Web Developer",
        period: "NOV 2016 - APR 2017",
        startDate: 1451628000000,
        endDate: 1483250400000,
        duration: 0,
        durationFraction: '-5',
        description: "DES_0015",
        portfolioUrl: null,
        portfolioImage: "img/vivaanuncios.png",
        technologiesId: [ 'HTML5', 'SASS', 'JS', 'JQUERY', 'TS', 'NG', 'KARMA', 'JAZMINE', 'GIT', 'JIRA', 'CONFLUENCE', 'NODEJS', 'ABXD' ],
        level: 2,
        color: 'yellow',
    },
    {
        id: 'PJ-0016',
        name: "Zaplabs LLC",
        type: "Web Developer",
        period: "APR 2017 - AUG 2017",
        startDate: 1483250400000,
        endDate: 1483250400000,
        duration: 0,
        durationFraction: '-5',
        description: "DES_0016",
        portfolioUrl: null,
        portfolioImage: "img/zaplabs.png",
        technologiesId: [ 'HTML5', 'SASS', 'JS', 'JQUERY', 'TS', 'NG', 'KARMA', 'JAZMINE', 'GIT', 'JIRA', 'CONFLUENCE', 'NODEJS', 'ABXD' ],
        level: 1,
        color: 'orange',
    },
    {
        id: 'PJ-0017',
        name: "DELL EMC",
        type: "Web Developer",
        period: "AUG 2017 - SEP 2017",
        startDate: 1483250400000,
        endDate: 1483250400000,
        duration: 0,
        durationFraction: '-5',
        description: "DES_0017",
        portfolioUrl: null,
        portfolioImage: "img/dell.png",
        technologiesId: [ 'HTML5', 'SASS', 'JS', 'JQUERY', 'TS', 'NG', 'KARMA', 'JAZMINE', 'GIT', 'JIRA', 'CONFLUENCE', 'NODEJS', 'ABXD' ],
        level: 2,
        color: 'red',
    },
    {
        id: 'PJ-0018',
        name: "Globant GLOW",
        type: "Web Developer",
        period: "SEP 2017 - JUL 2022",
        startDate: 1483250400000,
        endDate: 1641016800000,
        duration: 4,
        durationFraction: '',
        description: "DES_0018",
        portfolioUrl: null,
        portfolioImage: "img/globant.png",
        technologiesId: [ 'HTML5', 'SASS', 'JS', 'JQUERY', 'TS', 'NG', 'KARMA', 'JAZMINE', 'GIT', 'JIRA', 'CONFLUENCE', 'NODEJS', 'ABXD' ],
        level: 1,
        color: 'aqua',
    },
    {
        id: 'PJ-0019',
        name: "Disney",
        type: "Web Developer",
        period: "JUL 2022 - JUN 2023",
        startDate: 1641016800000,
        endDate: 1672552800000,
        duration: 0,
        durationFraction: '-5',
        description: "DES_0019",
        portfolioUrl: null,
        portfolioImage: "img/disnep.png",
        technologiesId: [ 'HTML5', 'SASS', 'JS', 'JQUERY', 'TS', 'NG', 'KARMA', 'JAZMINE', 'GIT', 'JIRA', 'CONFLUENCE', 'NODEJS', 'ABXD' ],
        level: 2,
        color: 'yellow',
    },
    {
        id: 'PJ-0020',
        name: "RockWell Automation",
        type: "Web Developer",
        period: "MAR 2023 - JUL 2023",
        startDate: 1672552800000,
        endDate: 1672552800000,
        duration: 0,
        durationFraction: '-5',
        description: "DES_0020",
        portfolioUrl: null,
        portfolioImage: "img/rockwell.png",
        technologiesId: [ 'HTML5', 'SASS', 'JS', 'JQUERY', 'TS', 'NG', 'KARMA', 'JAZMINE', 'GIT', 'JIRA', 'CONFLUENCE', 'NODEJS', 'ABXD' ],
        level: 3,
        color: 'orange',
    },
    {
        id: 'PJ-0021',
        name: "Pod Experience",
        type: "Web Developer",
        period: "JUL 2023 - ENE 2024",
        startDate: 1672552800000,
        endDate: 1704088800000,
        duration: 0,
        durationFraction: '-5',
        description: "DES_0021",
        portfolioUrl: null,
        portfolioImage: null,
        technologiesId: [ 'HTML5', 'SASS', 'JS', 'JQUERY', 'TS', 'NG', 'KARMA', 'JAZMINE', 'GIT', 'JIRA', 'CONFLUENCE', 'NODEJS', 'ABXD' ],
        level: 4,
        color: 'yellow',
    },
    {
        id: 'PJ-0022',
        name: "Pod Experience",
        type: "Web Developer",
        period: "ENE 2024 - ",
        startDate: 1704088800000,
        endDate: 1735711200000,
        duration: 1,
        durationFraction: '',
        description: "DES_0022",
        portfolioUrl: null,
        portfolioImage: "img/rockwell.png",
        technologiesId: [ 'HTML5', 'SASS', 'JS', 'JQUERY', 'TS', 'NG', 'KARMA', 'JAZMINE', 'GIT', 'JIRA', 'CONFLUENCE', 'NODEJS', 'ABXD' ],
        level: 4,
        color: 'yellow',
    }
];